---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: Build Site
    image: ruby:3.1.7
    commands:
      - gem install bundler jekyll
      - bundle install
      - bundle exec jekyll build
