---
title: thzinc
description: I'm Daniel James. I write things here when I feel like it.
author: Daniel James
timezone: America/Los_Angeles
email: daniel@thzinc.com
activitypub:
  username: "@thzinc@hachyderm.io"
  url: https://hachyderm.io/@thzinc
baseurl: ""
url: https://thzinc.com
markdown: kramdown
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "tags"
      type: "pages"
    values:
      layout: "tag"
mermaid:
  src: https://cdn.jsdelivr.net/npm/mermaid@11.4.0/dist/mermaid.min.js
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-mermaid
