# Site settings
title: thzinc
email: daniel@thzinc.com
description: > # this means to ignore newlines until "baseurl:"
  Personal site of Daniel James, a Christian, a husband,
  a software developer, and a maker
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thzinc.com" # the base hostname & protocol for your site
twitter_username: thzinc
github_username:  thzinc

# Build settings
markdown: kramdown
