---
title: thzinc
description: I'm Daniel James. I write things here when I feel like it.
author: Daniel James
timezone: UTC
email: daniel@thzinc.com
baseurl: ""
url: https://thzinc.com
markdown: kramdown
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "tags"
      type: "pages"
    values:
      layout: "tag"
plugins:
  - jekyll-sitemap
  - jekyll-feed
collections:
  projects:
    output: true
