import SocialProfile from "./SocialProfile"

export let socialProfiles = [
    new SocialProfile("Twitter", "https://twitter.com/thzinc", "twitter", ["primary", "microblog"]),
    new SocialProfile("Instagram", "https://instagram.com/thzinc", "instagram", ["primary", "photos"]),
    new SocialProfile("LinkedIn", "https://linkedin.com/in/danielijames", "linkedin", ["primary", "resume"]),
    new SocialProfile("GitHub", "https://github.com/thzinc", "github", ["primary", "development"]),
    new SocialProfile("Blog", "http://blog.thzinc.com", "tumblr", ["primary", "blog"]),
    new SocialProfile("thzinc-a-day", "http://thzincaday.thzinc.com", "tumblr", ["primary", "blog", "selfies"]),
    new SocialProfile("selfie stick-a-day", "http://selfiestickaday.thzinc.com", "tumblr", ["blog", "selfies"]),
    new SocialProfile("YouTube", "https://youtube.com/thzinc", "youtube", ["video"]),
    new SocialProfile("Flickr", "https://flickr.com/thzinc", "flickr", ["photos"]),
    new SocialProfile("SoundCloud", "https://soundcloud.com/thzinc", "soundcloud", ["audio"]),
    new SocialProfile("Amazon", "http://www.amazon.com/gp/pdp/profile/A6ZHPBH6JI81J", "amazon", ["consumer"]),
    new SocialProfile("Apache Lucene Mailing List", "http://lucene.472066.n3.nabble.com/template/NamlServlet.jtp?macro=user_nodes&user=485887", null, ["development", "forum"]),
    new SocialProfile("bit.ly", "http://bit.ly/u/thzinc", null, ["links"]),
    new SocialProfile("CHEEZburger", "http://app.cheezburger.com/thzinc/", null, ["photos", "memes"]),
    new SocialProfile("CodePlex", "http://www.codeplex.com/site/users/view/thzinc", null, ["development"]),
    new SocialProfile("Coderwall", "https://coderwall.com/thzinc", null, ["development", "blog", "forum"]),
    new SocialProfile("daPortfolio", "http://thzinc.daportfolio.com/", null, ["photos"]),
    new SocialProfile("del.icio.us", "http://del.icio.us/thzinc", "delicious", ["links"]),
    new SocialProfile("deviantART", "http://thzinc.deviantart.com/", "deviantart", ["photos"]),
    new SocialProfile("eBay", "http://www.ebay.com/sch/daniel_at_thzinc/m.html", null, ["consumer"]),
    new SocialProfile("Etsy", "https://www.etsy.com/people/thzinc", null, ["consumer"]),
    new SocialProfile("Facebook", "https://www.facebook.com/thzinc", "facebook", ["primary", "photos"]),
    new SocialProfile("CNN iReport", "http://ireport.cnn.com/people/thzinc", null, ["video"]),
    new SocialProfile("Khan Acadamy", "https://www.khanacademy.org/profile/thzinc/", null, ["education"]),
    new SocialProfile("LiveJournal", "http://thzinc.livejournal.com/", null, ["blog"]),
    new SocialProfile("MSDN", "https://social.msdn.microsoft.com/profile/thzinc", null, ["development"]),
    new SocialProfile("Pandora", "http://www.pandora.com/profile/daniel19309", null, ["audio"]),
    new SocialProfile("Photosynth", "https://photosynth.net/userprofilepage.aspx?user=thzinc", null, ["photos"]),
    new SocialProfile("Runkeeper", "https://runkeeper.com/user/thzinc/profile", null, ["health"]),
    new SocialProfile("Slashdot", "https://slashdot.org/%7Ethzinc", null, ["forum"]),
    new SocialProfile("SmartBear Forums", "https://community.smartbear.com/t5/user/viewprofilepage/user-id/15125", null, ["development", "forum"]),
    new SocialProfile("StackExchange", "http://stackexchange.com/users/1819033/daniel-james", null, ["development", "forum"]),
    new SocialProfile("StackOverflow", "http://stackoverflow.com/users/1653492/daniel-james", null, ["development", "forum"]),
    new SocialProfile("StackOverflow CV", "https://stackoverflow.com/cv/thzinc", null, ["resume"]),
    new SocialProfile("Steam", "https://steamcommunity.com/id/thzinc", null, ["gaming"]),
    new SocialProfile("Techdirt", "https://www.techdirt.com/profile.php?u=thzinc", null, ["forum"]),
    new SocialProfile("Ustream", "http://www.ustream.tv/channel/thzinc", null, ["video"]),
    new SocialProfile("Visual Studio UserVoice", "https://visualstudio.uservoice.com/users/17925881-thzinc", null, ["development", "forum"]),
    new SocialProfile("VMware Technology Network", "https://communities.vmware.com/people/thzinc", null, ["development", "forum"]),
    new SocialProfile("VMworld", "http://www.vmworld.com/people/daniel.james?view=profile", null, ["development", "forum"]),
    new SocialProfile("Wikipedia", "https://en.wikipedia.org/wiki/User:Thzinc", null, ["education"]),
];